---
RULE_CONFIG_VERSION: 0.0.2
VERSION_DATE: '2022-05-10'
ACTION_NAME: DUBLINCOREUPDEL
CONFIG:
  MONGO:
    DB_HOST: mongodb:27017
    DB_NAME: wf_hand
    USER: user
    PASS: pass
    AUTHENTICATE: false
  MODE: UPDATE
  RESTORE: true
