---
RULE_CONFIG_VERSION: 0.0.2
VERSION_DATE: '2022-05-10'
ACTION_NAME: PIDCREATE
CONFIG:
    CRED_FILE: "/usr/src/code/project/secrets/credentials.json"
    PREFIX: "11099"
    BASE_LOCATION: "https://repo.data.ingv.it"
    # if dry is true do not register pid on worldwide resolver
    DRY_RUN: false
    MONGO:
        DB_HOST: mongodb:27017
        DB_NAME: wf_hand
        USER: user
        PASS: pass
        AUTHENTICATE: false
